//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Dialg.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_DIALG_DIALOG                102
#define IDR_MAINFRAME                   128
#define IDD_BASEADDR                    129
#define IDD_INTRODUCE                   130
#define IDB_BITMAP2                     132
#define IDD_DIALOG1                     133
#define IDR_MENU1                       134
#define IDD_DIALOG2                     135
#define IDD_DIALOG3                     136
#define IDC_EDIT1                       1000
#define IDC_BUTTON_REV                  1001
#define IDC_BUTTON_ADD                  1002
#define IDC_BUTTON_DELE                 1003
#define IDC_BUTTON_CLEA                 1004
#define IDC_BUTTON_LOAD                 1005
#define IDC_BUTTON_LOAD2                1006
#define IDC_EDIT_SendData               1008
#define IDC_BUTTON_TX                   1009
#define IDC_BUTTON_STOPTX               1010
#define IDC_EDIT_TXNUM                  1015
#define IDC_TAB_REV                     1021
#define IDC_BUTTON_REX                  1022
#define IDC_BUTTON_ALLSELECT            1023
#define IDC_BUTTON_NONESELECT           1024
#define IDC_LIST_TXX                    1025
#define IDC_LIST1                       1026
#define IDC_LIST2                       1027
#define IDC_LIST3                       1028
#define IDC_LIST4                       1029
#define IDC_LIST5                       1030
#define IDC_LIST6                       1031
#define IDC_LIST7                       1032
#define IDC_LIST8                       1033
#define IDC_CHECK_TX1                   1034
#define IDC_CHECK_TX2                   1035
#define IDC_CHECK_TX3                   1036
#define IDC_CHECK_TX4                   1037
#define IDC_CHECK_TX5                   1038
#define IDC_CHECK_TX6                   1039
#define IDC_CHECK_TX7                   1040
#define IDC_CHECK_TX8                   1041
#define IDC_TAB_TX                      1042
#define IDC_TAB_RX                      1043
#define IDC_COMBO_BR                    1044
#define IDC_COMBO_RXBR                  1045
#define IDC_COMBO_JO                    1046
#define IDC_COMBO_TXBIT                 1047
#define IDC_COMBO_RXBIT                 1048
#define IDC_STATIC_DNUM2                1049
#define IDC_STATIC_DNUM3                1050
#define IDC_STATIC_DNUM4                1051
#define IDC_STATIC_DNUM5                1052
#define IDC_STATIC_DNUM6                1053
#define IDC_STATIC_DNUM7                1054
#define IDC_STATIC_DNUM8                1055
#define IDC_STATIC_DNUM9                1056
#define IDC_EDIT_DEPTH                  1057
#define IDC_CHECK_TIMETAG               1058
#define IDC_CHECK_TRUE                  1059
#define IDC_TAB_PULSE                   1060
#define IDC_EDIT_LPERIOD                1061
#define IDC_EDIT_LWORDDELAY             1062
#define IDC_EDIT_DELAYTIME              1063
#define IDC_EDIT_LTIME                  1064
#define IDC_EDIT_TIMENUM                1065
#define IDC_CHECK_LENABLE               1066
#define IDC_CHECK_WENABLE               1067
#define IDC_RADIO_UP                    1068
#define IDC_RADIO_DOWN                  1069
#define IDC_TAB_lable                   1070
#define IDC_COMBO_SD                    1071
#define IDC_CHECK_SD                    1072
#define IDC_CHECK_LABLE                 1073
#define IDC_CHECK_IN                    1074
#define IDC_CHECK_EXT                   1075
#define IDC_CHECK_REX                   1076
#define IDC_RADIO_INT                   1077
#define IDC_RADIO_INTT                  1078
#define IDC_RADIO_INQU                  1079
#define IDC_RADIO_SELEF                 1081
#define IDC_RADIO_NOMA                  1082
#define IDC_RADIO_WORD1                 1083
#define IDC_RADIO_WORD2                 1084
#define IDC_RADIO_WORK1                 1085
#define IDC_RADIO_WORK2                 1086
#define IDC_RADIO_INQURE                1087
#define IDC_CHECK_TMIT                  1088
#define IDC_CHECK_SAVE                  1089
#define IDC_CHECK_VIEW                  1090
#define IDC_CHECK_RXENABLE0             1091
#define IDC_CHECK_RXENABLE1             1092
#define IDC_CHECK_RXENABLE2             1093
#define IDC_CHECK_RXENABLE3             1094
#define IDC_CHECK_RXENABLE4             1095
#define IDC_CHECK_RXENABLE5             1096
#define IDC_CHECK_RXENABLE6             1097
#define IDC_CHECK_RXENABLE7             1098
#define IDC_BUTTON_RXENABLEALL          1099
#define IDC_BUTTON_RXENABLENONE         1100
#define IDC_BUTTON_RXENABLEOK           1101
#define IDC_CHECK1                      1102
#define IDC_CHECK2                      1103
#define IDC_CHECK3                      1104
#define IDC_CHECK4                      1105
#define IDC_CHECK5                      1106
#define IDC_CHECK6                      1107
#define IDC_CHECK7                      1108
#define IDC_CHECK8                      1109
#define IDC_BUTTON_RALL                 1110
#define IDC_BUTTON_RNO                  1111
#define IDC_CHECK_ADALLS                1112
#define IDC_CHECK_TXCONFIGTXALL         1113
#define IDC_CHECK_TXCONFIGRXALL         1114
#define IDC_CHECK_TRIGALL               1115
#define IDC_BTCANCEL                    1117
#define IDC_SETBCANCEL                  1118
#define IDC_BTTCANCEL                   1119
#define IDC_BTSCANCEL                   1120
#define ID_MEMU2                        32772
#define ID_MEMUWORD                     32774
#define ID_MEMUSD                       32775
#define ID_MEMUPULSE                    32777
#define ID_RESET                        32778
#define ID_MEMURESET                    32779

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
